import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./global.css";

import ThemeSwitch from "../components/ui/theme-switch";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Onlyy AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeSwitch />
        {children}
      </body>
    </html>
  );
}
